name: GWFrames
channels:
  - defaults
  - conda-forge
  - numba
  - moble
dependencies:
  - asn1crypto=0.24.0=py27_0
  - backports=1.0=py27_1
  - backports.functools_lru_cache=1.5=py27_1
  - backports.shutil_get_terminal_size=1.0.0=py27_2
  - backports_abc=0.5=py27_0
  - blas=1.0=mkl
  - bleach=3.1.0=py27_0
  - ca-certificates=2019.1.23=0
  - certifi=2018.11.29=py27_0
  - cffi=1.11.5=py27he75722e_1
  - chardet=3.0.4=py27_1
  - conda=4.6.4=py27_0
  - conda-env=2.6.0=1
  - configparser=3.7.1=py27_0
  - cryptography=2.4.2=py27h1ba5d50_0
  - cycler=0.10.0=py27_0
  - dbus=1.13.6=h746ee38_0
  - decorator=4.3.2=py27_0
  - entrypoints=0.3=py27_0
  - enum34=1.1.6=py27_1
  - expat=2.2.6=he6710b0_0
  - fftw=3.3.8=h7b6447c_3
  - fontconfig=2.13.0=h9420a91_0
  - freetype=2.9.1=h8a8886c_1
  - functools32=3.2.3.2=py27_1
  - futures=3.2.0=py27_0
  - glib=2.56.2=hd408876_0
  - gmp=6.1.2=h6c8ec71_1
  - gsl=2.4=h14c3975_4
  - gst-plugins-base=1.14.0=hbbd80ab_1
  - gstreamer=1.14.0=hb453b48_1
  - h5py=2.9.0=py27h7918eee_0
  - hdf5=1.10.4=hb1b8bf9_0
  - icu=58.2=h9c2bf20_1
  - idna=2.8=py27_0
  - intel-openmp=2019.1=144
  - ipaddress=1.0.22=py27_0
  - ipykernel=4.10.0=py27_0
  - ipython=5.8.0=py27_0
  - ipython_genutils=0.2.0=py27_0
  - ipywidgets=7.4.2=py27_0
  - jinja2=2.10=py27_0
  - jpeg=9b=h024ee3a_2
  - jsonschema=2.6.0=py27_0
  - jupyter=1.0.0=py27_7
  - jupyter_client=5.2.4=py27_0
  - jupyter_console=5.2.0=py27_1
  - jupyter_core=4.4.0=py27_0
  - kiwisolver=1.0.1=py27hf484d3e_0
  - libedit=3.1.20170329=h6b74fdf_2
  - libffi=3.2.1=hd88cf55_4
  - libgcc-ng=8.2.0=hdf63c60_1
  - libgfortran-ng=7.3.0=hdf63c60_0
  - libpng=1.6.36=hbc83047_0
  - libsodium=1.0.16=h1bed415_0
  - libstdcxx-ng=8.2.0=hdf63c60_1
  - libuuid=1.0.3=h1bed415_2
  - libxcb=1.13=h1bed415_1
  - libxml2=2.9.9=he19cac6_0
  - linecache2=1.0.0=py27_0
  - markupsafe=1.1.0=py27h7b6447c_0
  - matplotlib=2.2.3=py27hb69df0a_0
  - mistune=0.8.4=py27h7b6447c_0
  - mkl=2019.1=144
  - mkl_fft=1.0.10=py27ha843d7b_0
  - mkl_random=1.0.2=py27hd81dba3_0
  - nbconvert=5.3.1=py27_0
  - nbformat=4.4.0=py27hed7f2b2_0
  - ncurses=6.1=he6710b0_1
  - notebook=5.7.4=py27_0
  - numpy=1.15.4=py27h7e9f1db_0
  - numpy-base=1.15.4=py27hde5b4d6_0
  - openssl=1.1.1a=h7b6447c_0
  - pandoc=2.2.3.2=0
  - pandocfilters=1.4.2=py27_1
  - pathlib2=2.3.3=py27_0
  - pcre=8.42=h439df22_0
  - pexpect=4.6.0=py27_0
  - pickleshare=0.7.5=py27_0
  - pip=18.1=py27_0
  - prometheus_client=0.5.0=py27_0
  - prompt_toolkit=1.0.15=py27_0
  - ptyprocess=0.6.0=py27_0
  - pycosat=0.6.3=py27h14c3975_0
  - pycparser=2.19=py27_0
  - pygments=2.3.1=py27_0
  - pyopenssl=18.0.0=py27_0
  - pyparsing=2.3.1=py27_0
  - pyqt=5.9.2=py27h05f1152_2
  - pysocks=1.6.8=py27_0
  - python=2.7.15=h9bab390_6
  - python-dateutil=2.7.5=py27_0
  - pytz=2018.9=py27_0
  - pyzmq=17.1.2=py27he6710b0_2
  - qt=5.9.7=h5867ecd_1
  - qtconsole=4.4.3=py27_0
  - readline=7.0=h7b6447c_5
  - requests=2.21.0=py27_0
  - ruamel_yaml=0.15.46=py27h14c3975_0
  - scandir=1.9.0=py27h14c3975_0
  - send2trash=1.5.0=py27_0
  - setuptools=40.6.3=py27_0
  - simplegeneric=0.8.1=py27_2
  - singledispatch=3.4.0.3=py27_0
  - sip=4.19.8=py27hf484d3e_0
  - six=1.12.0=py27_0
  - sqlite=3.26.0=h7b6447c_0
  - subprocess32=3.5.3=py27h7b6447c_0
  - swig=3.0.10=0
  - terminado=0.8.1=py27_1
  - testpath=0.4.2=py27_0
  - tk=8.6.8=hbc83047_0
  - tornado=5.1.1=py27h7b6447c_0
  - traceback2=1.4.0=py27_0
  - traitlets=4.3.2=py27hd6ce930_0
  - unittest2=1.1.0=py27_0
  - urllib3=1.24.1=py27_0
  - wcwidth=0.1.7=py27h9e3e1ab_0
  - webencodings=0.5.1=py27_1
  - wheel=0.32.3=py27_0
  - widgetsnbextension=3.4.2=py27_0
  - xz=5.2.4=h14c3975_4
  - yaml=0.1.7=had09818_2
  - zeromq=4.3.1=he6710b0_3
  - zlib=1.2.11=h7b6447c_3
  - pip:
    - gwframes==0.0.0
    - quaternions==0.0.0
    - sphericalfunctions==0.0.0
prefix: /opt/conda
